version: '3.7'

services:
  app:
    image: <NAME-OF-DOCKER-IMAGE>
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - palworld
    ports:
      - 8211:8211/udp
    volumes:
      - <HOST-PATH-EXPOSED-TO-CONTAINER>:/palworld
    tty: true
    stdin_open: true

networks:
  palworld:
    name: palworld
    driver: overlay
